const data=[
    {"currency": "USD", "country": "United States", "amount_in_inr": 83.14},
    {"currency": "EUR", "country": "Eurozone", "amount_in_inr": 90.61},
    {"currency": "JPY", "country": "Japan", "amount_in_inr": 0.56},
    {"currency": "GBP", "country": "United Kingdom", "amount_in_inr": 104.43},
    {"currency": "AUD", "country": "Australia", "amount_in_inr": 53.27},
    {"currency": "CAD", "country": "Canada", "amount_in_inr": 62.53},
    {"currency": "CHF", "country": "Switzerland", "amount_in_inr": 90.31},
    {"currency": "CNY", "country": "China", "amount_in_inr": 11.42},
    {"currency": "SEK", "country": "Sweden", "amount_in_inr": 8.22},
    {"currency": "NZD", "country": "New Zealand", "amount_in_inr": 49.47},
    {"currency": "SGD", "country": "Singapore", "amount_in_inr": 61.27},
    {"currency": "HKD", "country": "Hong Kong", "amount_in_inr": 10.64},
    {"currency": "NOK", "country": "Norway", "amount_in_inr": 8.15},
    {"currency": "KRW", "country": "South Korea", "amount_in_inr": 0.07},
    {"currency": "TRY", "country": "Turkey", "amount_in_inr": 3.11},
    {"currency": "RUB", "country": "Russia", "amount_in_inr": 1.12},
    {"currency": "BRL", "country": "Brazil", "amount_in_inr": 15.94},
    {"currency": "ZAR", "country": "South Africa", "amount_in_inr": 4.84},
    {"currency": "MXN", "country": "Mexico", "amount_in_inr": 4.09},
    {"currency": "INR", "country": "India", "amount_in_inr": 1.00},
    {"currency": "THB", "country": "Thailand", "amount_in_inr": 2.37},
    {"currency": "MYR", "country": "Malaysia", "amount_in_inr": 18.04},
    {"currency": "IDR", "country": "Indonesia", "amount_in_inr": 0.0055},
    {"currency": "VND", "country": "Vietnam", "amount_in_inr": 0.0035},
    {"currency": "PKR", "country": "Pakistan", "amount_in_inr": 0.46},
    {"currency": "BDT", "country": "Bangladesh", "amount_in_inr": 0.79},
    {"currency": "PHP", "country": "Philippines", "amount_in_inr": 1.48},
    {"currency": "SAR", "country": "Saudi Arabia", "amount_in_inr": 22.16},
    {"currency": "AED", "country": "United Arab Emirates", "amount_in_inr": 22.64},
    {"currency": "ILS", "country": "Israel", "amount_in_inr": 23.96},
    {"currency": "EGP", "country": "Egypt", "amount_in_inr": 2.67},
    {"currency": "PLN", "country": "Poland", "amount_in_inr": 19.70},
    {"currency": "DKK", "country": "Denmark", "amount_in_inr": 12.15},
    {"currency": "CZK", "country": "Czech Republic", "amount_in_inr": 3.79},
    {"currency": "HUF", "country": "Hungary", "amount_in_inr": 0.22},
    {"currency": "RON", "country": "Romania", "amount_in_inr": 18.56},
    {"currency": "NGN", "country": "Nigeria", "amount_in_inr": 0.18},
    {"currency": "ARS", "country": "Argentina", "amount_in_inr": 0.27},
    {"currency": "COP", "country": "Colombia", "amount_in_inr": 0.022},
    {"currency": "PEN", "country": "Peru", "amount_in_inr": 22.24},
    {"currency": "CLP", "country": "Chile", "amount_in_inr": 0.10},
    {"currency": "LKR", "country": "Sri Lanka", "amount_in_inr": 0.27},
    {"currency": "KES", "country": "Kenya", "amount_in_inr": 0.57},
    {"currency": "GHS", "country": "Ghana", "amount_in_inr": 7.15},
    {"currency": "TZS", "country": "Tanzania", "amount_in_inr": 0.033},
    {"currency": "UGX", "country": "Uganda", "amount_in_inr": 0.022},
    {"currency": "MAD", "country": "Morocco", "amount_in_inr": 8.06},
    {"currency": "DZD", "country": "Algeria", "amount_in_inr": 0.61},
    {"currency": "JOD", "country": "Jordan", "amount_in_inr": 117.27}
  ]
  
  export default data